### ISSUE TITLE
cannot reach site on brwoser

### ISSUE THREAD

**Issue by Top-CMS** [ByteInternet/hypernode-docker#47]
Hi,

Successful installed the docker (docker.hypernode.com/byteinternet/hypernode-buster-docker-php74-mysql57:latest). But I have some problems with connections:

1. Cannot login with: 
`# SSH into the machine using the retrieved IP address. Example:
ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null app@172.17.0.2
# Or as the root user
ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@172.17.0.2`

I can login with:
`ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@localhost -p 1122`
2. In CLI, everything works fine....magerun2, php bin/magento, but I cannot access site on my webbrowser
tried:

- http://172.17.0.3:8025/
- http://172.17.0.3:8080/
- http://172.17.0.3:80/
- http://test.hypernode.local/
- http://test.hypernode.local:8025/
- http://test.hypernode.local:8080/

Also added to my windows hostfile
172.17.0.2		test.hypernode.local

How can I see the site in my browser?

**Comment by vdloo** [comment]
Hi, I'm not really familiar with running Docker on Windows at all but this more sounds like an issue with your Docker networking configuration in general instead of something related to this container. Perhaps looking inside the guest can help you rule out some problems:
- run `ip addr` to check if the IP address is indeed 172.17.0.2 in your situation
- run `netstat -tulpn` to see if the ports of the webservers are actually bound

If that all looks good make sure you 'expose' these ports to your host: https://docs.docker.com/config/containers/container-networking/#published-ports. How that works on Windows where the containers run inside some kind of virtual machine I do not know, but I'm sure that's something you can find with some googling.

btw if you can SSH to localhost on port 1122 perhaps you have also forwarded the other ports to localhost?
